### ISSUE TITLE
Bayrol Automatic CL PH

### ISSUE THREAD

**Issue by Coffee2k** [razem-io/ha-bayrol-cloud#1]
Hi,

first of all, thanks for your great work. The ph Sensor works fine.
The Redox and Temperature Sonsor are unavailable.

Bayrol Automatic CL PH
https://www.bayrol-poolaccess.de/webview/p/device.php?c=XXXXX&s=v2.03%20(240618-1133)

Best Regards

**Comment by Lu-do8121** [comment]
Hi, 
 
I cannot download the integration in HACS , it seems not be compatible

 
The version 2263be7 for this integration can not be used with HACS.


thanks

**Comment by razem-io** [comment]
@Lu-do8121Hi. Next time, open a separate issue. Fixed: https://github.com/razem-io/ha-bayrol-cloud/issues/2

If you still have issues, comment in the other issue. Thanks :)!

**Comment by Lu-do8121** [comment]
Hi , thank you very much ! 
Now I have the same problem as coffee2K I have only the PH sensor that appears temp and redox are unvailable , I do not know what you want but here is the html output  after log in: https://www.bayrol-poolaccess.de/webview/p/device.php?c=XXXXX&s=v1.40%20(220715)

Thanks :)!

**Comment by Lu-do8121** [comment]
I use the same equipement Bayrol Automatic CL PH

**Comment by razem-io** [comment]
@Lu-do8121 @Coffee2k  please update to version 0.1.2. There is a debug switch now. Check the README for more info (section "Using Debug Mode"). Then paste the raw html here.

**Comment by razem-io** [comment]
@Lu-do8121 thanks! Can you check if version 0.1.3 works for you?

**Comment by Lu-do8121** [comment]
@razem-io sorry not still only the PH sensor 

icon: mdi:bug
friendly_name: Pool Controller Debug Mode
debug_raw_html: <div><div class="gapp_ase" onclick="gotoapp(28354)"><span>App Link<span></div><div class="tab_data_link" onclick="document.location.href='device.php?c=XXXXX&s=v1.40 (220715)'"><div class="gstat_warning"></div><div class="tab_box stat_warning"><span>pH&nbsp;[pH]</span><h1>6.5</h1></div><div class="tab_box stat_warning"><span>Redox&nbsp;[mV]</span><h1>723</h1></div><div class="tab_box stat_warning"><span>Temp.&nbsp;[°C]</span><h1>19.0</h1></div><div class="tab_box "></div><div class="tab_info"><span>22ACL2-02745</span></br><span>Automatic Cl-pH</span></br><span>v1.40 (220715)</span></br><span><a href="device.php?c=XXXXX&s=v1.40 (220715)">Accès direct</a></div></div></div>

**Comment by razem-io** [comment]
@Lu-do8121  Can you update to 0.1.4 and post the debugging information as you did before? I have not changed the logic but added debugging info which hopefully helps me to see what is going wrong.

**Comment by Lu-do8121** [comment]
@razem-io yes please find it 

icon: mdi:bug
friendly_name: Pool Controller Debug Mode
debug_raw_html: <div><div class="gapp_ase" onclick="gotoapp(28354)"><span>App Link<span></div><div class="tab_data_link" onclick="document.location.href='device.php?c=XXXXX&s=v1.40 (220715)'"><div class="gstat_warning"></div><div class="tab_box stat_warning"><span>pH&nbsp;[pH]</span><h1>6.5</h1></div><div class="tab_box stat_warning"><span>Redox&nbsp;[mV]</span><h1>713</h1></div><div class="tab_box stat_warning"><span>Temp.&nbsp;[°C]</span><h1>13.0</h1></div><div class="tab_box "></div><div class="tab_info"><span>22ACL2-02745</span></br><span>Automatic Cl-pH</span></br><span>v1.40 (220715)</span></br><span><a href="device.php?c=XXXXX&s=v1.40 (220715)">Accès direct</a></div></div></div>

**Comment by Lu-do8121** [comment]
@razem-io even I updated the new version 0.1.5 is still the 0.1.2 on HA ? 
[test4.txt](https://github.com/user-attachments/files/17803155/test4.txt)

<img width="586" alt="Capture d’écran 2024-11-18 à 16 55 39" src="https://github.com/user-attachments/assets/3cd4b475-2abf-418b-b5a5-aaaae20d9ead">

thank you

**Comment by razem-io** [comment]
@Lu-do8121 ah, that is what I thought. Go to HACS -> click on Bayrol Cloud -> Press the 3 dots -> Download again -> Select version 0.1.5.

**Comment by Lu-do8121** [comment]
@razem-io do you think that information on whether filtration is active or not and the PH and redox alarm status can also be displayed ?

**Comment by razem-io** [comment]
@Lu-do8121 yes. Alarms should not be an issue. For the filtration, I have to check. I created 2 separate issues:

- https://github.com/razem-io/ha-bayrol-cloud/issues/4
- https://github.com/razem-io/ha-bayrol-cloud/issues/5

Follow those to get updates. I will close this issue, as it is solved for now.
